export const label = {
  position: '-top-1.5',
  fontSize: 'peer-placeholder-shown:text-sm',
  floated: {
    fontSize: 'text-[11px] peer-focus:text-[11px]',
  },
  before: {
    content: "before:content[' ']",
    display: 'before:block',
    boxSizing: 'before:box-border',
    width: 'before:w-[10px]',
    height: 'before:h-[6px]',
    mt: 'before:mt-[6.5px]',
    mr: 'before:mr-[4px]',
    borderColor: 'peer-placeholder-shown:before:border-transparent',
    borderRadius: 'before:rounded-tl-md',
    floated: {
      bt: 'before:border-t peer-focus:before:border-t-[2px]',
      bl: 'before:border-l peer-focus:before:border-l-[2px]',
    },
    pointerEvents: 'before:pointer-events-none',
    transition: 'before:transition-all',
    disabled: 'peer-disabled:before:border-transparent',
  },
  after: {
    content: "after:content[' ']",
    display: 'after:block',
    flexGrow: 'after:flex-grow',
    boxSizing: 'after:box-border',
    width: 'after:w-[10px]',
    height: 'after:h-[6px]',
    mt: 'after:mt-[6.5px]',
    ml: 'after:ml-1',
    borderColor: 'peer-placeholder-shown:after:border-transparent',
    borderRadius: 'after:rounded-tr-md',
    floated: {
      bt: 'after:border-t peer-focus:after:border-t-[2px]',
      br: 'after:border-r peer-focus:after:border-r-[2px]',
    },
    pointerEvents: 'after:pointer-events-none',
    transition: 'after:transition-all',
    disabled: 'peer-disabled:after:border-transparent',
  },
}
