name: CI

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'test'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GIT_TOKEN }}'
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Generate Environment Variables File for Production
        run: |
          echo "NEXT_PUBLIC_SANITY_STUDIO_URL=$NEXT_PUBLIC_SANITY_STUDIO_URL" >> .env.production
          echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL" >> .env.production
          echo "NEXT_PUBLIC_SANITY_DATASET=$NEXT_PUBLIC_SANITY_DATASET" >> .env.production
          echo "NEXT_PUBLIC_SANITY_PROJECT_ID=$NEXT_PUBLIC_SANITY_PROJECT_ID" >> .env.production
          echo "NEXT_PUBLIC_SANITY_ADMIN_TOKEN=$NEXT_PUBLIC_SANITY_ADMIN_TOKEN" >> .env.production
          echo "NEXT_PUBLIC_SANITY_USER_TOKEN=$NEXT_PUBLIC_SANITY_USER_TOKEN" >> .env.production
          echo "NEXT_PUBLIC_SANITY_REVALIDATE_SECRET=$NEXT_PUBLIC_SANITY_REVALIDATE_SECRET" >> .env.production
          echo "NEXT_PUBLIC_SANITY_API_VERSION=$NEXT_PUBLIC_SANITY_API_VERSION" >> .env.production
          echo "NEXT_PUBLIC_CONTACT_EMAIL=gnscott6@naver.com" >> .env.production
        env:
          NEXT_PUBLIC_SANITY_STUDIO_URL: ${{ secrets.NEXT_PUBLIC_SANITY_STUDIO_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_ADMIN_TOKEN: ${{ secrets.NEXT_PUBLIC_SANITY_ADMIN_TOKEN }}
          NEXT_PUBLIC_SANITY_USER_TOKEN: ${{ secrets.NEXT_PUBLIC_SANITY_USER_TOKEN }}
          NEXT_PUBLIC_SANITY_REVALIDATE_SECRET: ${{ secrets.NEXT_PUBLIC_SANITY_REVALIDATE_SECRET }}
          NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
        working-directory: ./apps/blog

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm turbo build
