name: retry_comment

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  retry:
    name: Build and Test
    timeout-minutes: 15
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: rerun
        uses: estroz/rerun-actions@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          comment_id: ${{ github.event.comment.id }}
