name: retry_comment

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  retry:
    name: Build and Test
    timeout-minutes: 15
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/retry')
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

       - name: Trigger build_pr workflow
         run: gh workflow run build_pr.yml --ref ${{ github.event.issue.pull_request.head.ref }}
